name: statistical-elements

dependencies:
  - algebra
  - base
  - equational-reasoning
  - ghc-typelits-knownnat
  - ghc-typelits-presburger
  - hmatrix
  - inline-r
  - MonadRandom
  - open-browser
  - random
  - statistics
  - vector

default-extensions:
  - DataKinds
  - GADTs
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall

library:
  source-dirs: src/
