name: statistical-elements

dependencies:
  - Chart
  - Chart-gtk
  - MonadRandom
  - attoparsec
  - base
  - hmatrix
  - lens
  - math-functions
  - permutation
  - random
  - refined
  - statistics
  - text
  - vector

default-extensions:
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall

library:
  source-dirs: src/
