name: statistical-elements

dependencies:
  - base
  - equational-reasoning
  - ghc-typelits-knownnat
  - ghc-typelits-presburger
  - hmatrix
  - vector

default-extensions:
  - DataKinds
  - GADTs
  - KindSignatures
  - RankNTypes
  - ScopedTypeVariables
  - TypeOperators

library:
  source-dirs: src/
