name: statistical-elements

dependencies:
  - attoparsec
  - base
  - equational-reasoning
  - ghc-typelits-knownnat
  - ghc-typelits-presburger
  - hmatrix
  - inline-r
  - MonadRandom
  - open-browser
  - random
  - statistics
  - text
  - vector

default-extensions:
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall

library:
  source-dirs: src/
