name: statistical-elements

dependencies:
  - algebra
  - base
  - equational-reasoning
  - ghc-typelits-knownnat
  - ghc-typelits-presburger
  - hmatrix
  - vector

default-extensions:
  - DataKinds
  - GADTs
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - RankNTypes
  - ScopedTypeVariables
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall

library:
  source-dirs: src/
